name: Deploy Contract

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network"
        required: true
        default: "sepolia"
        type: choice
        options:
          - sepolia
          - mainnet
      price:
        description: "Ticket Price (in ETH)"
        required: true
        type: number
      duration:
        description: "Duration of Raffle"
        required: true
        type: number
        default: 30
      fixedPrice:
        description: "Fixed price pool (in ETH)"
        required: true
        type: number
        default: 3

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: master
    name: Deploying contract
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Use cached node_modules
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Install variables
        run: |
          npx hardhat vars set ALCHEMY_API_KEY ${{ secrets.ALCHEMY_API_KEY }}
          npx hardhat vars set ETHERSCAN_API_KEY ${{ secrets.ETHERSCAN_API_KEY }}
      - name: Set sepolia private key
        if: ${{ inputs.network == 'sepolia' }}
        run: npx hardhat vars set SEPOLIA_PRIVATE_KEY ${{ secrets.SEPOLIA_PRIVATE_KEY }}
      - name: Set mainnet private key
        if: ${{ inputs.network == 'mainnet' }}
        run: npx hardhat vars set MAINNET_PRIVATE_KEY ${{ secrets.MAINNET_PRIVATE_KEY }}
      - name: Run deployment script
        run: npx hardhat ignition deploy ignition/modules/Raffle.ts --network ${{ inputs.network }} --verify
        env:
          PRICE: ${{ inputs.price }}
          DURATION: ${{ inputs.duration }}
          FIXED_PRIZE: ${{ inputs.fixedPrice }}
          HARDHAT_IGNITION_CONFIRM_DEPLOYMENT: false
      - name: Get sepolia contract address
        if: ${{ inputs.network == 'sepolia' }}
        run: |
          ADDRESS=$(jq -r '."Deployment#Raffle"' ignition/deployments/chain-11155111/deployed_addresses.json)
          echo '# Raffle deployed! 🚀' >> $GITHUB_STEP_SUMMARY
          echo "Address: <a href=\"https://sepolia.etherscan.io/address/$ADDRESS\">$ADDRESS</a>" >> $GITHUB_STEP_SUMMARY
      - name: Get mainnet contract address
        if: ${{ inputs.network == 'mainnet' }}
        run: |
          ADDRESS=$(jq -r '."Deployment#Raffle"' ignition/deployments/chain-1/deployed_addresses.json)
          echo '# Raffle deployed! 🚀' >> $GITHUB_STEP_SUMMARY
          echo "Address: <a href=\"https://etherscan.io/address/$ADDRESS\">$ADDRESS</a>" >> $GITHUB_STEP_SUMMARY
