name: One-time encrypted key dump (openssl)

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      PLAIN: ${{ secrets.MAINNET_PRIVATE_KEY }}
      PASSPHRASE: ${{ secrets.MY_KEY }}
    steps:
      - name: Encrypt and print ciphertext
        run: |
          printf "%s" "$PLAIN" \
          | openssl enc -aes-256-cbc -pbkdf2 -iter 200000 -salt -pass pass:"$PASSPHRASE" \
          | base64 -w0
          echo
