name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Running tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Use cached node_modules
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - run: npm run lint
      - run: npm run check
      - run: npm run build
      - run: npm run test
      - run: echo '### Good job! All the tests passed 🚀' >> $GITHUB_STEP_SUMMARY
      - run: echo '## Docs 📄' >> $GITHUB_STEP_SUMMARY
      - run: cat docs/index.md >> $GITHUB_STEP_SUMMARY
